services:
  - type: web
    name: football-ai
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_FOOTBALL_BASE_URL
        value: https://v3.football.api-sports.io
      - key: API_FOOTBALL_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
